WebShopApp/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System;
using WebshopApp.Data;
using WebshopApp.Data.Services;
using WebshopApp.Models;

namespace WebshopApp.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;
        public ActorsController(IActorsService service)
        {
          _service = service;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var data =  await _service.GetAllAsync();
            return View(data);
        }
        public async Task<IActionResult> CreateAsync()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAsync([Bind("FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> DetailsAsync(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails==null) 
            {
                return View("NotFound");
            }
            return View(actorDetails);
        }
        public async Task<IActionResult> EditAsync(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails==null)
            {
                return View("NotFound");
            }
            return View(actorDetails);
        }
        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, [Bind("Id, FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateAsync(id, actor);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails==null)
            {
                return View("NotFound");
            }
            return View(actorDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id, [Bind("Id, FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails==null)
            {
                return View("NotFound");
            }

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebShopApp/Controllers/CinemasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebshopApp.Data;

namespace WebshopApp.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ApplicationContext applicationContext;

        public CinemasController(ApplicationContext applicationContext)
        {
            this.applicationContext=applicationContext;
        }
        public async Task<IActionResult> IndexAsync()
        {
            var allCinemas = await applicationContext.Cinemas.ToListAsync();
            return View(allCinemas);
        }
    }
}

WebShopApp/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebshopApp.Data;

namespace WebshopApp.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationContext applicationContext;

        public MoviesController(ApplicationContext applicationContext)
        {
            this.applicationContext=applicationContext;
        }
        public async Task<IActionResult> IndexAsync()
        {
            var allMovies = await applicationContext.Movies
                .Include(n =>n.Cinema)
                .OrderBy(n=>n.Name).
                ToListAsync();

            return View(allMovies);
        }
    }
}

WebShopApp/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebshopApp.Data;

namespace WebshopApp.Controllers
{
    public class ProducersController : Controller
    {
        private readonly ApplicationContext applicationContext;

        public ProducersController(ApplicationContext applicationContext)
        {
            this.applicationContext=applicationContext;
        }
        public async Task<IActionResult> IndexAsync()
        {
            var allProducers = await applicationContext.Producers.ToListAsync();
            return View(allProducers);
        }
    }
}

WebShopApp/Views/Shared/NotFound.cshtml
<div class="row text-center">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">Content not found</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home</a>
    </div>
</div>

WebShopApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebshopApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebshopApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid"> 
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">MoviePassPro: Buy your e-tickets here!</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Movies" asp-action="Index"> <i class="badge-info bi-film"></i>Movies</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle ="dropdown" data-bs-toggle="dropdown" aria-haspopup ="true" aria-expanded="false">
                                <i class="badge-info bi-gear"></i>Management
                             </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i>Cinemas </a>
                                <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i>Producers </a>
                                <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i>Actors </a>
                            </div>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller ="Movies" asp-action="Filter" style="display:flex">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..."/>
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebshopApp 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>